### ISSUE TITLE
build fail because missing file

### ISSUE THREAD

**Issue by mmm2006** [Wilson13/AndroidBluetoothAudioCapture#1]
HI, I want to try your project in my pc. But it report error just like below:
Error:Failed to crunch file E:\android_source\HFP\AndroidBluetoothAudioCapture-master\AndroidBluetoothAudioCapture-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.0\res\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png into E:\android_source\HFP\AndroidBluetoothAudioCapture-master\AndroidBluetoothAudioCapture-master\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png

Can you help me to resolve it? Thanks

I don't know how to use it, Can you provide a guide about how to use your app? Thanks.

**Comment by Wilson13** [comment]
A quick google search landed me on this stackoverflow page, perhaps your project directory path was too long. Try moving it out to Desktop if you're on windows and give it a try =)

[Link to stackoverflow page](http://stackoverflow.com/a/39203167/1414598)
